application: stackarduino
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

inbound_services:
- warmup

default_expiration: "5d"

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /test.*
  login: admin  
  script: gaeunit.py
- url: /favicon.ico
  static_files: app/static/images/favicon.ico
  upload: app/static/images/favicon.ico
- url: /images
  static_dir: app/static/images
- url: /stylesheets
  static_dir: app/static/stylesheets
- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin
- url: /_ereporter
  script: $PYTHON_LIB/google/appengine/ext/ereporter/report_generator.py
  login: admin 
- url: /_ah/warmup
  script: application.py
  login: admin 
- url: /.*
  script: application.py
  
